on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
                run:
                    working-directory: ./frontend

        strategy:
            matrix:
                node-version: [18.x]
            
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            
          - name: Set up Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

    # frontend tests
          - name: Install Dependencies
            run: npm i
        
          - name: Build Next
            run: npm run build
        
          - name: Test Next
            run: npm run test