name: Code Formatting with Prettier

on:
  push:
    branches:
      # Branches to run code formatter in on each commit
      - main
  pull_request:
    branches:
      # Run code formatter on all branches that have a pull request open against main
      - '*'
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Format frontend
        run: |
          cd frontend
          npm install
          npm run format
          cd ..

      - name: Format backend
        run: |
          cd backend
          npm install
          npm run format
          cd ..

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Reformat all files with prettier
          branch: ${{ github.head_ref }}
